export const translations = {
    en: {
        title: "Feminist Data Art",
        about: "About",
        instructions: "Instructions",
        myGobelin: "My Data Art",
        aiChat: "AI Chat",
        socials: "Socials",
        support: "Support",
        myHistory: "Create based on my history",
        aiGorgon: "Create based on AI Gorgon",
        historyPlaceholder: "Enter your story...",
        submit: "Submit",
        clear: "Clear",
        edit: "Edit",
        share: "Share",
        copy: "Link copied",
        loading: "Loading...",
        fpsWarning: "Low performance detected. Try a smaller screen or simpler settings.",
        canvasError: "Cannot download or share an empty canvas.",
        startBls: "Start BLS",
        pauseBls: "Pause BLS",
        stopBls: "Stop BLS",
        calmDown: "Make Calmer",
        frequency: "BLS Frequency (Hz)",
        consentTitle: "Before Starting BLS",
        disclaimer: "This is an artistic visualization with elements of bilateral stimulation inspired by EMDR. It is not psychotherapy and does not replace working with a certified professional. Learn more at ",
        selfRegulation: "To stay grounded, try slow breathing (4 seconds in, 4 seconds out), look around the room to orient yourself, or visualize a safe, calming place.",
        contentWarning: "Stories may contain descriptions of violence. The 'Stop' button is always available and will replace the animation with a static warm fractal.",
        soft: "Soft",
        standard: "Standard",
        intense: "Intense",
        contraindications: "Do not use during severe dissociation, acute crisis, psychosis, or active suicidal thoughts. Seek professional help at ",
        privacy: "Your stories are anonymized and processed locally. You can choose not to save your story.",
        dontSave: "Do not save my story",
        accept: "Accept",
        decline: "Decline",
        whatIsBls: "What is BLS?",
        blsInfo: "Bilateral Stimulation (BLS) is when attention alternates between the left and right sides (visually, auditory, or tactile). It is used in EMDR therapy to process traumatic memories.",
        emdrInfo: "Eye Movement Desensitization and Reprocessing (EMDR) is a scientifically validated psychotherapy method for trauma. We use only an artistic visualization inspired by this method.",
        notTherapy: "Important: This is not therapy and does not replace working with a psychologist.",
        close: "Close"
    },
    ru: {
        title: "Феминистское искусство данных",
        about: "О проекте",
        instructions: "Инструкции",
        myGobelin: "Моё искусство данных",
        aiChat: "ИИ Чат",
        socials: "Социальные сети",
        support: "Поддержка",
        myHistory: "Создать на основе моей истории",
        aiGorgon: "ИИ Горгона",
        historyPlaceholder: "Введите вашу историю...",
        submit: "Отправить",
        clear: "Очистить",
        edit: "Редактировать",
        share: "Поделиться",
        copy: "Ссылка скопирована",
        loading: "Загрузка...",
        fpsWarning: "Обнаружена низкая производительность. Попробуйте меньший экран или упрощённые настройки.",
        canvasError: "Невозможно скачать или поделиться пустым холстом.",
        startBls: "Начать BLS",
        pauseBls: "Пауза BLS",
        stopBls: "Остановить BLS",
        calmDown: "Сделать спокойнее",
        frequency: "Частота BLS (Гц)",
        consentTitle: "Перед началом BLS",
        disclaimer: "Это художественная визуализация с элементами двусторонней стимуляции по мотивам EMDR. Не является психотерапией и не заменяет работу с сертифицированным специалистом. Узнайте больше на ",
        selfRegulation: "Для саморегуляции попробуйте медленное дыхание (4 секунды вдох, 4 секунды выдох), осмотрите комнату для ориентации или представьте безопасное, спокойное место.",
        contentWarning: "Истории могут содержать описания насилия. Кнопка «Остановить» всегда доступна и заменяет анимацию на статичный тёплый фрактал.",
        soft: "Мягко",
        standard: "Стандарт",
        intense: "Интенсивнее",
        contraindications: "Не используйте при выраженной диссоциации, остром кризисе, психозе или активных суицидальных мыслях. Обратитесь за профессиональной помощью на ",
        privacy: "Ваши истории анонимизируются и обрабатываются локально. Вы можете запретить сохранение истории.",
        dontSave: "Не сохранять мою историю",
        accept: "Принять",
        decline: "Отклонить",
        whatIsBls: "Что такое BLS?",
        blsInfo: "Двусторонняя стимуляция (BLS) — это когда внимание попеременно смещается между левой и правой стороной (визуально, звуком или касанием). Используется в EMDR-терапии для переработки травматических воспоминаний.",
        emdrInfo: "Десенсибилизация и переработка движением глаз (EMDR) — научно подтверждённый метод психотерапии травм. Мы используем только художественную визуализацию по мотивам метода.",
        notTherapy: "Важно: Это не терапия и не заменяет работу с психологом.",
        close: "Закрыть"
    },
    es: {
        title: "Arte de Datos Feminista",
        about: "Acerca de",
        instructions: "Instrucciones",
        myGobelin: "Mi Arte de Datos",
        aiChat: "Chat de IA",
        socials: "Redes Sociales",
        support: "Apoyo",
        myHistory: "Crear basado en mi historia",
        aiGorgon: "IA Gorgona",
        historyPlaceholder: "Ingresa tu historia...",
        submit: "Enviar",
        clear: "Limpiar",
        edit: "Editar",
        share: "Compartir",
        copy: "Enlace copiado",
        loading: "Cargando...",
        fpsWarning: "Se detectó un rendimiento bajo. Prueba con una pantalla más pequeña o configuraciones más simples.",
        canvasError: "No se puede descargar o compartir un lienzo vacío.",
        startBls: "Iniciar BLS",
        pauseBls: "Pausar BLS",
        stopBls: "Detener BLS",
        calmDown: "Hacer más tranquilo",
        frequency: "Frecuencia BLS (Hz)",
        consentTitle: "Antes de comenzar BLS",
        disclaimer: "Esta es una visualización artística con elementos de estimulación bilateral inspirada en EMDR. No es psicoterapia y no reemplaza el trabajo con un profesional certificado. Más información en ",
        selfRegulation: "Para mantenerte conectado, intenta respirar lentamente (4 segundos inspirar, 4 segundos exhalar), observa la habitación para orientarte o visualiza un lugar seguro y tranquilo.",
        contentWarning: "Las historias pueden contener descripciones de violencia. El botón 'Detener' siempre está disponible y reemplazará la animación con un fractal cálido estático.",
        soft: "Suave",
        standard: "Estándar",
        intense: "Intenso",
        contraindications: "No utilices durante disociación severa, crisis aguda, psicosis o pensamientos suicidas activos. Busca ayuda profesional en ",
        privacy: "Tus historias se anonimizan y procesan localmente. Puedes optar por no guardar tu historia.",
        dontSave: "No guardar mi historia",
        accept: "Aceptar",
        decline: "Rechazar",
        whatIsBls: "¿Qué es BLS?",
        blsInfo: "La estimulación bilateral (BLS) es cuando la atención alterna entre los lados izquierdo y derecho (visual, auditivo o táctil). Se utiliza en la terapia EMDR para procesar recuerdos traumáticos.",
        emdrInfo: "La Desensibilización y Reprocesamiento por Movimientos Oculares (EMDR) es un método de psicoterapia validado científicamente para el trauma. Utilizamos solo una visualización artística inspirada en este método.",
        notTherapy: "Importante: Esto no es terapia y no reemplaza el trabajo con un psicólogo.",
        close: "Cerrar"
    }
};

export const pages = {
    about: {
        en: "About",
        ru: "О проекте",
        es: "Acerca de",
        name: "About"
    },
    instructions: {
        en: "Instructions",
        ru: "Инструкции",
        es: "Instrucciones",
        name: "Instructions"
    },
    myGobelin: {
        en: "My Data Art",
        ru: "Моё искусство данных",
        es: "Mi Arte de Datos",
        name: "My Data Art",
        path: "/my-gobelin"
    },
    aiChat: {
        en: "AI Chat",
        ru: "ИИ Чат",
        es: "Chat de IA",
        name: "AI Chat",
        path: "/ai-chat"
    },
    socials: {
        en: "Socials",
        ru: "Социальные сети",
        es: "Redes Sociales",
        name: "Socials"
    },
    support: {
        en: "Support",
        ru: "Поддержка",
        es: "Apoyo",
        name: "Support"
    }
};
