export const pages = {
    about: { name: 'About', ru: 'О проекте', es: 'Acerca de' },
    instructions: { name: 'Instructions', ru: 'Инструкции', es: 'Instrucciones' },
    myGobelin: { name: 'My Data Art', ru: 'Мой дата-арт', es: 'Mi Arte de Datos' },
    aiChat: { name: 'AI Chat', ru: 'AI чат', es: 'Chat IA' },
    socials: { name: 'Socials', ru: 'Соцсети', es: 'Redes Sociales' },
    support: { name: 'Support', ru: 'Поддержать', es: 'Apoyar' }
};

export const translations = {
    en: {
        download: 'Download',
        share: 'Share',
        placeholder: "Ask a question about feminism...",
        detailsToggle: { open: "Hide Details", closed: "Show Details" },
        namePlaceholder: "Name (e.g., Anna)",
        countryPlaceholder: "Country",
        cityPlaceholder: "City",
        save: "Save",
        reset: "Reset",
        clear: "Clear",
        clearHistory: "Clear History",
        regenerate: "Regenerate",
        copy: "Copy",
        errorResponse: "An error occurred. Please try again later.",
        fallbackResponse: "Feminism is a movement advocating for equal rights and opportunities for women across social, political, and economic spheres. (Please verify information with official sources.)",
        modalTitle: "User Details",
        canvasError: "Cannot download or share an empty canvas.",
        myHistory: "Create based on my history",
        aiGorgon: "Create based on AI Gorgon",
        historyPlaceholder: "Enter your story...",
        submit: "Submit",
        edit: "Edit",
        disclaimer: "Disclaimer",
        disclaimerText: "This is an artistic visualization with bilateral stimulation (BLS) inspired by EMDR. It is not psychotherapy and does not replace professional help. Consult a certified specialist for therapy.",
        warning: "Content may be triggering. Use grounding techniques (e.g., deep breathing, orienting in the room). Do not use in case of dissociation, crisis, psychosis, or suicidal thoughts without professional support.",
        privacy: "Your text is processed locally and not stored unless you choose to save it.",
        consent: "I Understand and Agree",
        guidelines: "Learn more about EMDR guidelines",
        startBls: "Start BLS",
        pauseBls: "Pause BLS",
        stopBls: "Stop BLS",
        calmDown: "Make Calmer",
        frequency: "BLS Frequency (Hz)",
        soft: "Soft",
        standard: "Standard",
        intense: "Intense",
        survey: "How do you feel?",
        distress: "Distress",
        tension: "Tension",
        calm: "Calm",
        submitSurvey: "Submit"
    },
    ru: {
        download: 'Скачать',
        share: 'Поделиться',
        placeholder: "Задайте вопрос о феминизме...",
        detailsToggle: { open: "Скрыть детали", closed: "Показать детали" },
        namePlaceholder: "Имя (например, Анна)",
        countryPlaceholder: "Страна",
        cityPlaceholder: "Город",
        save: "Сохранить",
        reset: "Сбросить",
        clear: "Очистить",
        clearHistory: "Очистить историю",
        regenerate: "Перегенерировать",
        copy: "Скопировать",
        errorResponse: "Произошла ошибка. Пожалуйста, попробуйте снова.",
        fallbackResponse: "Феминизм — это движение за равные права и возможности для женщин в социальной, политической и экономической сферах. (Пожалуйста, проверьте информацию в официальных источниках.)",
        modalTitle: "Данные пользователя",
        canvasError: "Невозможно скачать или поделиться пустым холстом.",
        myHistory: "Создать на основе моей истории",
        aiGorgon: "Создать на основе общения с AI Горгоной",
        historyPlaceholder: "Введите вашу историю...",
        submit: "Отправить",
        edit: "Редактировать",
        disclaimer: "Отказ от ответственности",
        disclaimerText: "Это художественная визуализация с элементами двусторонней стимуляции (BLS) по мотивам EMDR. Это не психотерапия и не заменяет профессиональную помощь. Обратитесь к сертифицированному специалисту для терапии.",
        warning: "Контент может быть триггерным. Используйте техники заземления (например, глубокое дыхание, ориентация в комнате). Не используйте при выраженной диссоциации, кризисе, психозе или суицидальных мыслях без профессиональной поддержки.",
        privacy: "Ваш текст обрабатывается локально и не сохраняется, если вы не выберете сохранение.",
        consent: "Я понимаю и соглашаюсь",
        guidelines: "Узнать больше о рекомендациях по EMDR",
        startBls: "Начать BLS",
        pauseBls: "Приостановить BLS",
        stopBls: "Остановить BLS",
        calmDown: "Сделать спокойнее",
        frequency: "Частота BLS (Гц)",
        soft: "Мягко",
        standard: "Стандарт",
        intense: "Интенсивнее",
        survey: "Как вы себя чувствуете?",
        distress: "Дистресс",
        tension: "Напряжение",
        calm: "Спокойствие",
        submitSurvey: "Отправить"
    },
    es: {
        download: 'Descargar',
        share: 'Compartir',
        placeholder: "Haz una pregunta sobre feminismo...",
        detailsToggle: { open: "Ocultar detalles", closed: "Mostrar detalles" },
        namePlaceholder: "Nombre (ej., Anna)",
        countryPlaceholder: "País",
        cityPlaceholder: "Ciudad",
        save: "Guardar",
        reset: "Restablecer",
        clear: "Limpiar",
        clearHistory: "Limpiar historial",
        regenerate: "Regenerar",
        copy: "Copiar",
        errorResponse: "Ocurrió un error. Por favor, intenta de nuevo.",
        fallbackResponse: "El feminismo es un movimiento que aboga por los derechos y oportunidades iguales para las mujeres en las esferas social, política y económica. (Por favor, verifica la información con fuentes oficiales.)",
        modalTitle: "Detalles del usuario",
        canvasError: "No se puede descargar ni compartir un lienzo vacío.",
        myHistory: "Crear basado en mi historia",
        aiGorgon: "Crear basado en AI Gorgona",
        historyPlaceholder: "Ingresa tu historia...",
        submit: "Enviar",
        edit: "Editar",
        disclaimer: "Descargo de responsabilidad",
        disclaimerText: "Esta es una visualización artística con estimulación bilateral (BLS) inspirada en EMDR. No es psicoterapia ni reemplaza la ayuda profesional. Consulta a un especialista certificado para terapia.",
        warning: "El contenido puede ser desencadenante. Usa técnicas de conexión a tierra (por ejemplo, respiración profunda, orientación en la habitación). No uses en caso de disociación, crisis, psicosis o pensamientos suicidas sin apoyo profesional.",
        privacy: "Tu texto se procesa localmente y no se almacena a menos que elijas guardarlo.",
        consent: "Entiendo y estoy de acuerdo",
        guidelines: "Aprende más sobre las guías de EMDR",
        startBls: "Iniciar BLS",
        pauseBls: "Pausar BLS",
        stopBls: "Detener BLS",
        calmDown: "Hacer más tranquilo",
        frequency: "Frecuencia BLS (Hz)",
        soft: "Suave",
        standard: "Estándar",
        intense: "Intenso",
        survey: "¿Cómo te sientes?",
        distress: "Malestar",
        tension: "Tensión",
        calm: "Calma",
        submitSurvey: "Enviar"
    }
};
