export const pages = {
    about: { name: 'About', ru: 'О проекте', es: 'Acerca de' },
    instructions: { name: 'Instructions', ru: 'Инструкции', es: 'Instrucciones' },
    myGobelin: { name: 'My Data Art', ru: 'Мой дата-арт', es: 'Mi Arte de Datos' },
    aiChat: { name: 'AI Chat', ru: 'AI чат', es: 'Chat IA' },
    socials: { name: 'Socials', ru: 'Соцсети', es: 'Redes Sociales' },
    support: { name: 'Support', ru: 'Поддержать', es: 'Apoyar' }
};

export const translations = {
    en: {
        download: 'Download',
        share: 'Share',
        placeholder: "Ask a question about feminism...",
        detailsToggle: { open: "Hide Details", closed: "Show Details" },
        namePlaceholder: "Name (e.g., Anna)",
        countryPlaceholder: "Country",
        cityPlaceholder: "City",
        save: "Save",
        reset: "Reset",
        clear: "Clear",
        clearHistory: "Clear History",
        regenerate: "Regenerate",
        copy: "Copy",
        errorResponse: "An error occurred. Please try again later.",
        fallbackResponse: "Feminism is a movement advocating for equal rights and opportunities for women across social, political, and economic spheres. (Please verify information with official sources.)",
        modalTitle: "User Details",
        canvasError: "Cannot download or share an empty canvas.",
        myHistory: "Create based on my history",
        aiGorgon: "Create based on AI Gorgon",
        historyPlaceholder: "Enter your story...",
        submit: "Submit",
        edit: "Edit"
    },
    ru: {
        download: 'Скачать',
        share: 'Поделиться',
        placeholder: "Задайте вопрос о феминизме...",
        detailsToggle: { open: "Скрыть детали", closed: "Показать детали" },
        namePlaceholder: "Имя (например, Анна)",
        countryPlaceholder: "Страна",
        cityPlaceholder: "Город",
        save: "Сохранить",
        reset: "Сбросить",
        clear: "Очистить",
        clearHistory: "Очистить историю",
        regenerate: "Перегенерировать",
        copy: "Скопировать",
        errorResponse: "Произошла ошибка. Пожалуйста, попробуйте снова.",
        fallbackResponse: "Феминизм — это движение за равные права и возможности для женщин в социальной, политической и экономической сферах. (Пожалуйста, проверьте информацию в официальных источниках.)",
        modalTitle: "Данные пользователя",
        canvasError: "Невозможно скачать или поделиться пустым холстом.",
        myHistory: "Создать на основе моей истории",
        aiGorgon: "Создать на основе общения с AI Горгоной",
        historyPlaceholder: "Введите вашу историю...",
        submit: "Отправить",
        edit: "Редактировать"
    },
    es: {
        download: 'Descargar',
        share: 'Compartir',
        placeholder: "Haz una pregunta sobre feminismo...",
        detailsToggle: { open: "Ocultar detalles", closed: "Mostrar detalles" },
        namePlaceholder: "Nombre (ej., Anna)",
        countryPlaceholder: "País",
        cityPlaceholder: "Ciudad",
        save: "Guardar",
        reset: "Restablecer",
        clear: "Limpiar",
        clearHistory: "Limpiar historial",
        regenerate: "Regenerar",
        copy: "Copiar",
        errorResponse: "Ocurrió un error. Por favor, intenta de nuevo.",
        fallbackResponse: "El feminismo es un movimiento que aboga por los derechos y oportunidades iguales para las mujeres en las esferas social, política y económica. (Por favor, verifica la información con fuentes oficiales.)",
        modalTitle: "Detalles del usuario",
        canvasError: "No se puede descargar ni compartir un lienzo vacío.",
        myHistory: "Crear basado en mi historia",
        aiGorgon: "Crear basado en AI Gorgona",
        historyPlaceholder: "Ingresa tu historia...",
        submit: "Enviar",
        edit: "Editar"
    }
};
